name: tf_paginated_list
description: A starting point for Dart libraries or applications.
version: 1.0.0
publish_to: none
# homepage: https://www.example.com

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  tf_data_streamer:
    git:
      url: https://github.com/rahul-badgujar/tf_data_streamer_dart_package.git
      ref: main

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
